services:
  market-fetcher:
    build: .
    container_name: poly_fetcher
    restart: unless-stopped
    volumes:
      - ./polymarket_cache:/app/data
      - ../config.py:/app/config.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
