services:
  market-fetcher:
    build: .
    container_name: wallet_scoring
    restart: on-failure
    volumes:
      - ../data-cache/polymarket_cache:/app/data
      - ../config.py:/app/config.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
